### ISSUE TITLE
BattlEyeConnectEventHandler

### ISSUE THREAD

**Issue by Nullfati** [mvries/BattleNET#39]
How to make BattlEyeConnectEvent return string or bool?

**Comment by mvries** [comment]
You can change event stuff [here](https://github.com/mvries/BattleNET/blob/master/BattleNET/BattlEyeDisconnectEventArgs.cs).

**Comment by Nullfati** [comment]
But how b.BattlEyeConnected += BattlEyeConnected; return in variable bool?

**Comment by DomiStyle** [comment]
BattlEyeConnected can't return a bool, you need to handle all connection related code inside of the event.
Take a look at the BattlEyeConnectEventArgs inside the connect event.

You can see it here: https://github.com/mvries/BattleNET/blob/master/BattleNET%20client/Program.cs#L102

args.ConnectionResult is what you want.

**Comment by mvries** [comment]
Closing for now, ty @DomiStyle.
